#!/usr/bin/env python
import argparse
import logging
from os.path import exists, isdir

from animagic.anime import sync_all_anime

def main():
    parser = argparse.ArgumentParser(description='Command-line frontend for animagic.')
    parser.add_argument("-c", "--config", default="config.yaml")
    parser.add_argument("-d", "--directory")
    parser.add_argument("-t", "--torrent-directory")
    parser.add_argument("-l", "--log-file", default="animagic.log")
    parser.add_argument("task", help="The task for the script. Usually people want this to be 'sync'")
    args = parser.parse_args()

    config_file = args.config
    if not exists(config_file):
        print("Config file {0} does not exist.".format(config_file))
        return 1

    anime_directory = args.directory
    if anime_directory:
        if not isdir(anime_directory):
            print("Anime directory specified does not exist or is not a directory.")
            return 1
    else:
        print("Please specify the root directory of your anime collection with -d")
        return 1

    torrent_directory = args.torrent_directory
    if torrent_directory:
        if not isdir(torrent_directory):
            print("Torrent directory specified does not exist or is not a directory.")
            return 1
    else:
        print("Please specify the torrent download directory with -t")
        return 1

    logging.basicConfig(filename=args.log_file, level=logging.DEBUG)
    logging.info("CLI Client Run")
    sync_all_anime(config_file, anime_directory, torrent_directory)

if __name__ == "__main__":
    main()
